services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: realtime_chat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  postgres_data:

