[project]
name = "chat-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kolykonon", email = "kononikhinnikolay@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
chat-service = "chat_service:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
